name: iOS build

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'

      - uses: actions/checkout@v2
      
      - name: static to dylib
        run: |
          brew install ldid

      - name: Native build
        run: |
          cd Natives
          mkdir build
          cd build
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DPLATFORM=OS64 -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""
          cmake --build . --config Release --target pojavexec PojavLauncher
          cd ../..
          mkdir -p Natives/build/Release-iphoneos/PojavLauncher.app/Frameworks
          cp Natives/build/Release-iphoneos/libpojavexec.dylib Natives/build/Release-iphoneos/PojavLauncher.app/Frameworks/

      - name: Java Build
        run: |
          cd JavaApp
          chmod +x gradlew
          ./gradlew clean build
          cd ..
          mkdir Natives/build/Release-iphoneos/PojavLauncher.app/libs
          cp JavaApp/build/libs/PojavLauncher.jar Natives/build/Release-iphoneos/PojavLauncher.app/launcher.jar
          
      - name: Sign and Package IPA
        run: |
          mkdir Payload
          mv Natives/build/Release-iphoneos/PojavLauncher.app Payload/
          ldid -Sentitlements.xml Payload/PojavLauncher.app/PojavLauncher
          zip -r PojavLauncher.ipa Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher
          path: PojavLauncher.ipa

